# Generated by Django 6.0.2 on 2026-02-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_optional', models.BooleanField(default=False)),
                ('difficulty_rating', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to='games.game')),
            ],
        ),
    ]
