# Generated by Django 6.0.2 on 2026-02-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosses', '0001_initial'),
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(help_text='Número de tentativas nesta sessão')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('is_victory', models.BooleanField(default=False, help_text='Derrotou o boss nesta sessão?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bosses.boss')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builds.build')),
            ],
        ),
    ]
